---
- name: Process user namespace
  include_role:
    name: project
  vars:
    project: 'user{{ item }}'
    display_name: 'User{{ item }} Project'

- name: Give user{{ item }} access to user project
  shell: "oc policy add-role-to-user admin user{{ item  }} -n user{{ item }}"

- name: Give user{{ item }} access to shared project
  shell: "oc policy add-role-to-user view user{{ item  }} -n {{ shared_project }}"
