---
- name: Pause deployment
  shell: oc rollout pause dc/tutorial-web-app -n {{ configmap_namespace }}
  register: pause_dc
  failed_when: pause_dc.stderr != '' and 'is already paused' not in pause_dc.stderr

- name: Check if ConfigMap already exists
  shell: oc get configmap {{ configmap_name }} -n {{ configmap_namespace }}
  register: check_webapp_configmap
  failed_when: false

- template:
    src: extra-services.yaml.j2
    dest: /tmp/extra-services.yaml
    
- name: Apply the web app ConfigMap
  shell: oc apply -f /tmp/extra-services.yaml -n {{ configmap_namespace }}

- name: Mount ConfigMap
  shell: oc set volume dc/tutorial-web-app --add -m /etc/webapp/ --type=configmap --configmap-name={{ configmap_name }} -n {{ configmap_namespace }}
  when: check_webapp_configmap.rc != 0   

- name: Change webapp operator CR #override with V2 DIL walkthroughs
  shell: oc patch webapp tutorial-web-app-operator -n webapp --type=merge  -p '{"spec":{"template":{"parameters":{"WALKTHROUGH_LOCATIONS":"{{ wt_locations }}"}}}}'

- name: Resume deployment
  shell: oc rollout resume dc/tutorial-web-app -n {{ configmap_namespace }}
